services:
  pg_chainlink:
    image: postgres
    ports:
      - '5432:5432'
    env_file:
      - database.env
    volumes:
      - ./pgdata/:/var/lib/postgresql/data
  chainlink:
    image: 'smartcontract/chainlink:1.3.0'
    ports:
      - '6688:6688'
    env_file:
      - .env
    depends_on:
      - pg_chainlink
    volumes:
      - ./chainlink-volume/:/chainlink/
    command: node start --password /chainlink/password.txt --api /chainlink/apicredentials.txt
